<div id='footer'>
<script>$(document).ready(function(){(function() {$('.sideBar').html(' <div id="shareBtns"> <!--Facebook--> <div id="facebook"> <a href="http://www.facebook.com/ZooFaroo" target="_blank"><img src="images/facebookFollow.png" height="25" width="25" alt="Find us on Facebook!" style="border:none;"/></a> </div> <div id="twitter"> <!--Twitter--> <a href="https://twitter.com/ZooFaroo" target="_blank"><img src="images/twitterFollow.png" height="25" width="25" alt="Follow us on Twitter!" style="border:none;"/></a> </div> <!--Google--> <div id="plus1"> <link href="https://plus.google.com/103958829492703792482" rel="publisher" /> <a href="https://plus.google.com/103958829492703792482?prsrc=3" style="text-decoration: none;"><img src="images/googlePlusFollow.png" height="25" width="25" alt="Follow us on Twitter!" style="border:none;"/></a> </div> </div>');var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;po.src = 'https://apis.google.com/js/plusone.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);})();confirmUserObject.confirmUser();bcObject.bcInjector();quickSearchObject.quickSearch('<? echo $p; ?>', '<? echo $state; ?>', '<? echo $city; ?>', '<? echo $offerNeed; ?>', '<? echo $category; ?>');});</script>
<script></script>
<g:plusone size="medium" annotation="none"></g:plusone>
<div id="likeBtn"><div class="fb-like" data-href="http://www.zoofaroo.com" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true" data-font="arial"></div></div>
<div id="footer-menu">
<a class="fMenuBtn" href="login.html">login</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="home.html">home</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="register.html">register</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="contact.html">contact</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="forget.html">forgot password?</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="edit.html">edit your account</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="about.html">What is ZooFaroo?</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="donate.html">donate</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="search.html">advanced search</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="post.html">leave post</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="blog">blog</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="directory.html">user directory</a>&nbsp;<br>&nbsp;<a class="fMenuBtn" href="smarter.html">barter smarter</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="sitemap.html">sitemap</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="legal/ZooFaroo_Terms_of_Use.pdf">terms of use</a>&nbsp;|&nbsp;<a class="fMenuBtn" href="legal/ZooFaroo_Privacy_Policy.pdf">privacy policy</a>&nbsp;|&nbsp;&copy;&nbsp;2012&nbsp;ZooFaroo, LLC&nbsp;&nbsp;</div>
</div><!--footer-->

</div><!--wrapper-->
</body>
</html>